### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#11]
# Road map for MVP

- [X] define technology stack
 
At this moment, it is meteor.js with a mongo backend, a private ethereum blockchain, web3.js

## general setup	
  - [x] buy and furbish server
  - [x] setup private chain (http://paratii-chain.gerbrandy.com/)
  - [x] set up front end (http://paratii.gerbrandy.com/)
  - [x] set up staging server
  - [x] continuous integration #4
  - [x] continuous deployment #4 

## Set up meteor routes and basic templates

  - [x] define routes and templates #3

## graphical basic design of the frontend	

On the basis of the material here:
https://github.com/Paratii-Video/paratii-design/blob/master/mvp-design/

  - [x]	implement general stylesheets, classes, icons, basic html structure
  - [x] implement design of video player #12

## Authentication and security	

  - [x] integrate basic workflow meteor account (signin, signup)
  - [x] password reseting etc (need to define a policy
  - [x] add basic ethereum account management #8 
	
## Wallet/Profile #47 

- [x] finish wallet design and specs 
- [x] make it work (i.e. transfer tokens, eth, set password, etc)

## Video Player
	
  - [x] integrate a video player
  - [x] implement design of video player #12
  - [x]	 integrate (non-incentivized) p2p sharing with the video player #9
  - [ ]	 integrate incentivized p2p sharing with the video player (out of scope)

## Play List			
 
- [ ] implement playlist logic (meteor only) #10 
- [ ] implement grapichal design #5 
- [ ] port data and logic to blockchain (optional)

## Votes and views	

This regards the counters for views, and the upvotes

  - [ ] implement counters on meteor server level (no blockchain) #13
  - [ ]	second iteration implemented in blockchain 

## Token management
	
token implementation on bllockchain	
  - [x] write and deploy erc20 contract #50
  - [ ]	 create mining contract (out of scope)
		
### Player integration

  - [ ]	 define advertisement presentation UX 
  - [ ]	 implement in player
		

## Backend

this concerns the management interface to view and administer all data (users, videos, views, votes, etc etc)

- [ ] define specifications (we have nothing yet)

# Out of Scope of MVP (for now)

## Videos

- [ ]  uploads

## Ads

- [ ] uploading of ads 
- [ ]	advertisement: economic integration	

## Mining
  - [ ]		specs of proof-of-view
  - [ ]		implement in web service
  - [ ]		implement in player

##	Attention market (basics)	
  - [ ]		specs and doc
  - [ ]		implement in web service
  - [ ]		implement in player
		
- [ ]	attention market (advanced)	
		

- [ ]	crowdsourced curation (flagging videos)

**Comment by felipegaucho** [comment]
Closing this in favour of #114 .
