### ISSUE TITLE
Path to Pilot

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-player#114]
# Path to Pilot

### Embedabbility #101 

- [x] Define if we need preset embed sizes/versions (i.e. Mini Mode & Tiny Mode)
- [ ] Integrate device-sniffing code in the player (status @geckoslair?).
- [x] Precise documentation on how to embed our player. #116 

### "Anonymous" usability
- [ ] Make it possible to play videos without being logged in #105

### Video Purchase (PPV)
- [x] Adjust PPV contract scheme. https://github.com/Paratii-Video/paratii-contracts/issues/2
- [x] Finish + choose UI proposal.
- [ ] Implement new modal for purchase.
- [ ] Make all videos bought by user be included in a playlist “My Purchased Videos”, that appears to him by default under “Playlists” by on the dropdown menu of the Playlist page.

### Playlists
- [ ] Finish UI proposal including search functionality, flags, and other missing elements.
- [ ] Define and Implement playlist logic (meteor only) 
- [ ] Implement search on playlists #10 
- [ ] Port data and logic to blockchain @jellegerbrandy is still drawing the line here.

### Curation / Votes / Views		
- [ ] Implement counters for views (same as for the lines - this goes registered on our test chain already?) #13 
- [ ] Implement counters for upvotes / downvotes (upvotes send the video to the “my liked videos” user playlist, which can be automatically created after the user has liked one video at least).
- [ ] Implement an input field for suggesting a tag, in the “paused video screen”.
- [ ] Implement recommendations (“You may also enjoy”) at end of video, based on the video’s tags. On testnet, this could work along these lines https://github.com/Paratii-Video/wiki/wiki/Towards-a-Decentralised-Recommendation-Engine, or in a simpler manner.
- [ ] Implement counter for flags.

### Sharing
- [x] Implement “share” button on “paused video screen”, which returns a copyable link (not traceable, at current state, right @geckoslair?)
- [x] Implement UI for Mini sharing modals.
- [x] Implement UI for Tiny sharing modals.

### "Upload"
- [ ] Finish UI proposal: creators will have fields for “title”, “description”, “tags” (up to 5), “thumbnail”, and “the file”. They won’t be able to explicitly create playlists still.
- [x] https://github.com/Paratii-Video/transcoder/commit/5fdccdcc86bf5959456e8fe5c5111505ef3682b0
- [ ] Have a multiplexing server available. If we only serve files prepared by us, this does not need to be a “live” server and we could use some external services. If however we want to have “live upload” functionality (i.e. users can upload and suitable file variants are immediately available) we need a on-the-fly mechanism.
- [ ] Automatically create playlist via tags.
- [ ] Devise Content Policy.
- [ ] Write Terms of service. 

### "My videos"
- [ ] Finish UI proposal (still a simple list with thumbs + organized data).
- [ ] Categorize stats we want to present and fetch them only (i.e. improve descriptions). #72 
- [ ] Implement page design.

### P2P incentivization
 - [ ] Put together basic IPFS stats (per-bit accounting). #103
 - [ ] UI proposal for element that displays current activity/stats of the node in the p2p network (i.e 97kbps upload / 65 kbps download).
 - [ ] Implement the display above in the front-end.
 - [ ] Create event that triggers a `settlement` function every time a threshold is reached.

### Paratii Incentivization
- [ ] Implement a flow in which: whenever user registers his email, a confirmation message is sent to it, with a custom link. When the users clicks on it to confirm his email, he’s redirected to a “thank you” message in a modal on his “wallet” screen in the player, indicating he now has PTI credits.
 - [ ] Implement PTI 'protoincentives' in a contract (#13 is a prerequisite). #110 
 - [ ] Create modal that shows guide to protoincentives ("Earn more PTI..." - a chart). Whenever user has not enough PTI to watch something he wants, he can click on a helper and go to this.

### Transaction History
 - [ ] UI proposal taking per-bit accounting into account.  ( no pun intended ¯\_(ツ)_/¯ )
 - [ ] Implement design. 
 - [ ] Fetch `settlement` records in the transaction history (show accounting debt/credit). We can add a unit “X bits and show every `settlement` recorded transaction (which are different from sends/receives/purchases) with the accounting result (bits) and equivalent +/- (in PTI) - like a receipt.

## Admin
- [x] Management interface to view and administer users; see, edit ~~and upload~~ videos; organize content; users and roles; monitor usage; traffic sources. #100 
- [ ] Setup an approval videos must undergo (by us) before being listed by the app.

## Optimization
- [ ] Get some performance statistics (load time on various devices, size) of the app 
- [ ] Optimize!
