### ISSUE TITLE
player page todo

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#27]
- [x]  1 - Apply volume with control (can be a dropdown that goes up and there's a vertical slider w/ grey + purple)
- [x]    2 - Apply streaming/progress bar,
- [x]      3 - Add total video duration / current timing on video being played;
- [x]      4 -Add buttons left and right of play button: go to next video on playlist, go to previous video on playlist (or rewind current one if it's on the middle);
- [x]      5 - Adjust spacing between the icons below video description;
- [x]      6 -Add producer thumbnail/avatar;
- [x]      7 -Put full screen button on the far right :slightly_smiling_face: ;
- [x]      8 - When press play, hide the menu and everything else (already done according to matheus). A click anywhere pauses the video and brings up the "paused video screen" again;
- [x]      9 - When lateral menu comes up, the grey on the background can fade in, instead of abruptly appearing;
- [x]      10 - When the video has a price in PTI (pay per view), make the price appear in purple box below video description (if it's free - standard -, no box) [clicking on this purple box will bring up a pop up confirming the transaction, then one more click and it plays - we haven't got this popup yet];
- [x]      11 - Make the amount that the user has in his wallet appear in purple next to his avatar when the menu opens (see mockup below), then clicking on it takes us to "my wallet" (we might need a stronger indicator that it's a link :slightly_smiling_face: );
- [ ]    12 -  (optional, if you guys can do it easily) Add the slight grey line/shadow separating the user profile picture from the rest of the menu and separating the name of the screen, on top of the player, from the rest of the screen, under it (note on the mockup below);
- [ ]    13 - controls auto width when fullscreen
- [ ]  14 - implement like/dislike logic and UX: cf #34

**Comment by lupape** [comment]
13 and 14 - we can implement share, favorite and producer relationship when we finished all other priorities.

**Comment by lupape** [comment]
#27 tasks: 3 7 8 9 - right! tks.

**Comment by eliawk** [comment]
@jellegerbrandy could you close this one?

**Comment by jellegerbrandy** [comment]
closing because obsolete
