### ISSUE TITLE
wallet page todo list

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#28]
* Art  is here: https://github.com/Paratii-Video/paratii-design/blob/master/mvp-design/artboards/mvp-wallet-2.png
* http://paratii.gerbrandy.com/wallet

  

- [ ] Implement design
- [x] Restore wallet functionality
- [x ] Show seed button
- [x] Implement PTI transfer (we fake it in mongodb) #39 
- [x] implement history of transactions (we fake it in mongodb) #40
- [ ] use models instead of prompt: #38

**Comment by jellegerbrandy** [comment]
http://paratii.gerbrandy.com/wallet

**Comment by jellegerbrandy** [comment]
replaced by #47
