### ISSUE TITLE
profile page todo list

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#29]
**see #47  for updated information**

 * https://github.com/Paratii-Video/paratii-design/blob/master/mvp-design/artboards/mvp-profile-altbt.png
 * http://paratii.gerbrandy.com/account

 - [ ] Implement design
 - [x] Implement upload/remove profile image
 - [ ] Implement change password 
 - [ ] Implement reset password
 - [ ] ~~Implement reputation points list~~ (this has low priority for now)

**Comment by jellegerbrandy** [comment]
https://github.com/Paratii-Video/paratii-design/blob/profile/mvp-design/artboards/mvp-profile-altbt.png

**Comment by geckoslair** [comment]
@jellegerbrandy  "Change password and restore password" features doesn't affect wallet at this time. right? "restore password" can be done using double opt-in using email?

**Comment by jellegerbrandy** [comment]
**change password** works like this:

 1. User clicks "change password"
 1. User is asked to provide the old password
 1. Wallet is opened and regenerated
 1. Password is changed on server

**reset password** works like this:

 1. user clicks "reset password"
 1. user is asked for the 12-word seed
 1. user is asked for new password
 1. wallet is regenerated using seed and new password
 1. password is reset on server(*)

(*) We should prove to the server that the seed corresponds to the users's ethereum account The server knows the user's ethereum account. in theory, the wallet can sign a message, send it to the serer, and the server can use that as proof. In practice (for MVP puproses, not for production) we'll just check if the new wallet generates the correct address.
