### ISSUE TITLE
🌊 v0.0.1 RELEASE 🚀

### ISSUE THREAD

**Issue by felipegaucho** [Paratii-Video/paratii-player#319]
> 🌊 This release brings a first version of the standalone player, to be shared (and _reshareable_) mainly over Twitter. Its purpose is to demonstrate browser-to-browser p2p streaming working with acceptable performance; the account and wallet generation process handled within the player itself; and also to give early hints of browsing/navigation. It is of course under heavy development. ⚡

# :world_map: What's left to release

- [x] Short-cut our thumb titles with "..." https://github.com/Paratii-Video/paratii-player/issues/298
- [x] Polish the controls for twitter https://github.com/Paratii-Video/paratii-player/issues/318
- [x] Limit tags not to overflow the paused screen https://github.com/Paratii-Video/paratii-player/issues/282
- [x] Make loaders for those waiting moments and integrate the p2p stats here https://github.com/Paratii-Video/paratii-player/issues/154
- [x] In the wallet, let users know it's not their fault that they're poor (it's demo guys ¯\_(ツ)_/¯)  https://github.com/Paratii-Video/paratii-player/issues/329

# 🔦 Highlights

### It works!

Might sound simplistic, but it's exciting to see pure p2p streaming happening over libp2p, with in-browser nodes, on existing content platforms like Twitter. This opens up the possibility for incentivisation in ways that have never been done before. Thanks to @ya7ya for slaying the dragons when it comes to those shuffling all those chunks around!

### Cross-platform support

It works not only in Twitter, but also in Telegram (directly inside the mobile app) and in Facebook's feed, through Open Graph (but only if posted as a comment, for now). You can also embed it in your [Wordpress site with oEmbed](https://github.com/Paratii-Video/paratii-embed#oembed-and-wordpress), and there's much more coming. Thanks @geckoslair for making this possible... and understandable - see [the documentation here](https://github.com/Paratii-Video/paratii-embed)) :)

### There's a wallet in your player!

In order to take part in micropayments or interact with smart contracts, users must have tokens, and a place to store them. The Paratii player creates a local wallet for users, stores their encrypted keystore on the browser, and allows for small transactions to be performed semiautonomously. Soon, these mechanism will be incorporated into a safer multilayered scheme (unnecessary until we have real $).

### Account creation in a flash

The above means you _don't have_ to log in to enjoy the content you seek. Any user is able to "play" a video or browse within the player "anonymously" (💪 @eliawk ). If you notice the sign up option, you can just input an email and password, and became a registered user who'll be able to withdraw + move around funds.

# 📏 Benchmarks
- _**Writing in Progress**_ _(Build time / ipfs instance load time /....)_

# ✅ Release Checklist

- **Robustness and quality**
  - Ensure that all tests are passing, this includes:
   - [ ] unit
   - [ ] ?
- **Documentation**
  - [ ] Ensure that README.md is up to date
  - [x] Ensure that embedding documentation is up to date
  - [x]  Create the release issue
- **Communication**
   - [ ] Medium post
   - [ ] Twitter (share Around the Block trailer on the player)
   - [ ] Telegram
   - [ ] Reddit
   - [ ] Facebook

# 🙌🏽 Want to contribute?
Please first have a quick look at our contribution guidelines [here](https://github.com/Paratii-Video/wiki/blob/master/CONTRIBUTING.md). Be on the lookout for issues labeled with something that catches your eyes and sparks your interest. And feel free to drop a line on [gitter](https://gitter.im/Paratii-Video) about anything relevant to the issue - from a UX suggestion to a bug fix.

**Comment by jrgarou** [comment]
@felipegaucho I made some changes and create a pull request for them:
https://github.com/Paratii-Video/paratii-player/pull/343

**Comment by felipegaucho** [comment]
👏
