### ISSUE TITLE
transaction history

### ISSUE THREAD

**Issue by jellegerbrandy** [Paratii-Video/paratii-player#66]
this work is done on the branch ` transaction-history`

 - the whole transaction history (of all users) will be saved in a Meteor.collection on the server. 

 - the app on sendPTI and sentEth will (1) do the transaction on the blockchain and (2) if the transaction is successful, write the relevant data to the collection
- we will wathc the blockchain for new transactions, and if such transactions wer not added by the rpevious step, they will be added automagically. 
- note that all this maangement will need to be done *server side*.

- [x] first iteration: all code client side, and in session
- [x]  define collections
     - [x] create collection and subscription
     - [x] do synching prevous history with blockchain serverside, and only when needed
     - [x] do a `web3.filter('latest').watch` thing to constantly update the data
     - [x] patch sendPTI to add a description (and perhaps other data) to the transaction
     - [x] path sendEth to add a description (and perhaps other data) to the transaction
     - [x] if user's address is "from", value should show up as negative (with a "-"  and/or red) on the screen, if it is "to", as positive.

 - [ ] implement infinite scroll #73
 - [x] we need better descriptions #72
 - [ ] make it searchable #74 
 - [x] ~show profile info #75~
- [ ] fix up transaction history view #138

**Comment by jellegerbrandy** [comment]
closing in favor of separate actionabile issues.
